// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAuYZYBXtCHo_GjVVCANPX4jcSfxGnQiU',
    appId: '1:951616862332:web:ba8555f5da98e71dfe71f9',
    messagingSenderId: '951616862332',
    projectId: 'fvidlearn',
    authDomain: 'fvidlearn.firebaseapp.com',
    storageBucket: 'fvidlearn.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdKM8WzUuUXjNDS5k_FOaKh66nqAS0lWw',
    appId: '1:951616862332:android:a3805fdb0cdda5abfe71f9',
    messagingSenderId: '951616862332',
    projectId: 'fvidlearn',
    storageBucket: 'fvidlearn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0X_Om7Pdrpu0GaAouq-KMdxr6xFtSiBo',
    appId: '1:951616862332:ios:f9936473a5c41a7dfe71f9',
    messagingSenderId: '951616862332',
    projectId: 'fvidlearn',
    storageBucket: 'fvidlearn.appspot.com',
    iosBundleId: 'com.example.videoSharingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0X_Om7Pdrpu0GaAouq-KMdxr6xFtSiBo',
    appId: '1:951616862332:ios:f9936473a5c41a7dfe71f9',
    messagingSenderId: '951616862332',
    projectId: 'fvidlearn',
    storageBucket: 'fvidlearn.appspot.com',
    iosBundleId: 'com.example.videoSharingApp',
  );
}
